language: ruby
rvm:
  - 2.0.0-p247
before_install:
  - gem update --system
  - gem --version
script: "bundle exec jekyll build"
branches:
  only:
    - master
cache:
  bundler
  directories:
    - /var/lib/gems/2.0.0
    - /home/caleb/.gem/ruby/2.0.0
    - /usr/share/rubygems-integration/2.0.0
    - /usr/share/rubygems-integration/all
